server:
  port: 8081
  servlet:
    session:
      cookie:
        name: ASSESSIONID
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG



togglz:
  enabled: true
  features:
    OAUTH2.enabled: false
  console:
    use-management-port: false
    enabled: true
    secured: false



oauth2:
  issuer: 'http://localhost:8080/oauth'
  login-redirect-uri: 'http://localhost:8080/login?redirectUri=%s'
  clients:
    keycloak-client:
      client-id: 'keycloak-client'
      authorization-code-lifetime: 60
      access-token-lifetime: 600
      redirect-uris:
        - 'http://localhost:8082/auth/realms/test/broker/demo-authorization-server/endpoint'
      scopes: ['openid']
      pkceMethod: S256
      jwksUrl: 'http://client/jwks'
  jwk:
    key-id: 'demo-server'
    algorithm: 'RS512'
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCpR5hJAawgiGeL
      nCz7JZiqAd6qS/gT9jHSUSPYLSr7erAIyK8eZJlrKB6BHpFsPOjiAmBKrVTSNr1j
      Uf4u4ZaWnMK/HkHfWWwpdDbhRpaGyC+Ia00u569dLgvNo1FJ2bJSkE4KMlQ8MYJu
      lpuwSd9MI1mqvyKQRiorXnNHiY+CvCa8spXZAo8hZlSRev2J3SQgKumvAtqAHB20
      81an9gHX+K47PmHAVeZMnDjEbooaXiuHJBkSkbqCKitnr3j+fZrfQa3RtBK6TEzM
      dMGu5Xgzj3bl4i+GMROMPMyx5LPP3fWUbLcyBXLtuVoh8KzJBPXwNlG5Q+wE3KOw
      GI6YRfMNAgMBAAECggEBAIPUS9ZfRQs471qcT7Nuvgt31U5OR25URsyBgCa0Vkru
      avUMRMSol4oJ/meTxLDEZqDMNO0zO2FSW/9jNU6RRFMa1dc82xPzcfZ+mNarwEJK
      2CmnVr52k+0/FNYaoA2hSexekUgDlfIipG83Pxv1C78hsIz2uRYebmzD64cErAyk
      8he+LDILJGiZWmdsYV/FfY7iwjwSVgkmFpYX7VIzwMptMgCjjwKm1TiLeLAz+dcW
      G45Pxe/OIgvMLuiNY+nRZuIxqpVyz2fHVb1U8fIED5zryP8imhVyf/1U6Fz3Wgy2
      Z7FnhYtXG2F7mi1Orsp8rU2NkPG2skjbuCXtY7g1OcECgYEA2AWrJEVrPrFrk0fs
      CxZfLt+Iz9gXdxyAiB/sngjn/WfMrKlWNdgGhUMrTzIL8srN34SLmpqqWbUuh90P
      fp8joQv3BOoT3nQm6t/OYt33IIB2hK9x0dYnrAd5s7yD5WjGSxdmPc2maUV94Wmo
      uJx4upQ44HY4zAhsGruqP8t8tYkCgYEAyJtwwdbjJuMik3Vc8eN7Zz3DNcimx9bp
      dkg9oLmdCO52KJqyacWr1518bDJeNPv/4HKdDBQbkvMh7Su5IBDQ/7xvw2cus2c/
      PyvOaSJMZuxAVMepEbyxoSRK2To8yYbmm9U9AxLKNASrfNkuTVmu6aO+IS6e4elz
      EWX2YU9+tGUCgYB+T1IycySyE6uDAprSINKm5a1pWkDeNJwy+/eusCZ11SuoCZuP
      ADFP2maIeArkfBDEkQvP6n+Q1I/QgUF+GC8NC6H0DapweBoJW7Ohu4e0SWkDTFKR
      D1dDD1vp7GBy00Cex5/Qo16aTze7hbxRtawh7GkVVgr/wizztKdnheP1gQKBgQCr
      x2cTpWXXq9G0wV/4hZnrOxkI2ivundpGfe+/zJFqz3+An489QZY3yNR9ddfzuQJP
      +PUAHcvK1sVraPBaQ+wjwQFXKujzmOqwtltG7abMz2r67gmZdaIJYaFySAs7anfY
      Yw2erx1U09bgzrx2YeCEksFBesF0o8nz0QLcKw1NfQKBgFe8633U9NrOBc75OSdn
      smVs6vF/MjdCxklXP6WSNkB8MszMcxA0NT7tp1e3eGoXbeKGV87qxcnFCC+kNO0D
      fnVPR5fOZzLMvw0YgheSUHifKxDTheBNe4QdI8uLfBigC/rnPNWySDJUizdzl8xR
      6PHtRH6M1N57spTVKudeKmOb
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqUeYSQGsIIhni5ws+yWY
      qgHeqkv4E/Yx0lEj2C0q+3qwCMivHmSZaygegR6RbDzo4gJgSq1U0ja9Y1H+LuGW
      lpzCvx5B31lsKXQ24UaWhsgviGtNLuevXS4LzaNRSdmyUpBOCjJUPDGCbpabsEnf
      TCNZqr8ikEYqK15zR4mPgrwmvLKV2QKPIWZUkXr9id0kICrprwLagBwdtPNWp/YB
      1/iuOz5hwFXmTJw4xG6KGl4rhyQZEpG6giorZ694/n2a30Gt0bQSukxMzHTBruV4
      M4925eIvhjETjDzMseSzz931lGy3MgVy7blaIfCsyQT18DZRuUPsBNyjsBiOmEXz
      DQIDAQAB
      -----END PUBLIC KEY-----